baseURL: "https://toss.asia"
title: TOSS
paginate: 6


enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: The Other Side of the Story
    description: "The Other Side of the Story"
    keywords: [Blog, Portfolio, PaperMod]
    author: TOSS
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false


    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        #favicon: "<link / abs url>"
        #favicon16x16: "<link / abs url>"
        #favicon32x32: "<link / abs url>"
        #apple_touch_icon: "<link / abs url>"
        #safari_pinned_tab: "<link / abs url>"

    label:
        text: "TOSS"
        #icon: '/logo.png'
        #iconHeight: 45

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "The Other Side of the Story \U0001F49b"
        Content: For the youth. By the youth.

    socialIcons:
        - name: instagram
          url: "https://www.instagram.com/toss.my/"
        - name: email
          url: "mailto:tosshelp.my@gmail.com"
        - name: linktree
          url: "https://linktr.ee/TheOtherSideofTheStory"



    analytics:
        google:
             SiteVerificationTag: "jitfTggbGUJICiejUl-c1ZbxRPUf759u2Yh8slWhc5M"
#        bing:
#            SiteVerificationTag: "XYZabc"
#        yandex:
#            SiteVerificationTag: "XYZabc"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: false # hide on single page
        image: "<image path/url>"
        alt: "<alt text>"
        caption: "<text>"
        relative: false # To use relative path for cover image, used in hugo Page-bundles




    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content", "tags", "categories"]
menu:
    main:
        - identifier: home
          name: Home
          url: /
          pre: home
          weight: 10
        - identifier: search
          name: Search
          url: /search/
          pre: search
          weight: 30
        - identifier: about
          name: About
          url: /about/
          pre: info
          weight: 20
        - identifier: archive
          name: Archive
          url: /archive/
          pre: archive
          weight: 40
        #- identifier: contact
        #  name: Contact
        #  url: /contact/
         # pre: send
         # weight: 50
        - identifier: events
          name: Events
          url: /events/
          pre: calendar
          weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

cover:
    image: "<image path/url>"
    # can also paste direct link from external site
    # ex. https://i.ibb.co/K0HVPBd/paper-mod-profilemode.png
    alt: "<alt text>"
    caption: "<text>"
    relative: false # To use relative path for cover image, used in hugo Page-bundles
